feat : initial commit of a task
rel1c-hub/book-store pull request #12
Opened 2024-05-20 06:48 UTC by rel1c-hub

2024-05-20 21:59 UTC, Eidenn005 approved these changes
LGTM

2024-05-21 09:45 UTC, yevheniisynytsia requested changes
Well done! Left some comments

2024-05-21 09:45 UTC, yevheniisynytsia commented on src/main/java/mate/academy/bookstore/model/Book.java
> +    private Set<Category> categories = new HashSet<>();
please exclude from equals and hashcode and to string

2024-05-21 09:45 UTC, yevheniisynytsia commented on src/main/java/mate/academy/bookstore/serivce/impl/BookServiceImpl.java
>          return bookMapper.toDto(bookRepository.save(book));
please add validation for categories' ids that are passed by user
like 109094203132132 that is not in db

2024-05-21 09:45 UTC, yevheniisynytsia commented on src/main/resources/db/changelog/changes/02-add-books.yaml
>                    name: author
please do not modify the changesets that were merged to main

your colleagues will have checksum fail and will have to fix that problems

2024-05-23 11:09 UTC, closed without merging