Dto branch
rel1c-hub/book-store pull request #2
Opened 2024-04-23 18:33 UTC by rel1c-hub

Add BookDto.class as a response DTO, and CreateBookRequestDto.class as a request DTO
Add Mapstruct and mappers
Return and accept DTOs on the service layer
Add BookController with methods:
public List getAll()
public BookDto getBookById(Long id)
public BookDto createBook(CreateBookRequestDto bookDto)
Add missing methods in the BookService and BookRepository
Create and use EntityNotFoundException class
Remove CommandLineRunner bean

2024-04-23 20:15 UTC, azzilian requested changes
Please do check your imports I beliece i is better if your project will be in the root directory

2024-04-23 20:15 UTC, azzilian commented on src/main/java/mate/academy/bookstore/mapper/BookMapper.java
> +import org.mapstruct.Mapper;
please do check packagename

2024-04-23 20:15 UTC, azzilian commented on src/main/java/mate/academy/bookstore/dto/BookDto.java
> +    private String coverImage;
Why isbn is missed?

2024-04-23 21:06 UTC, rel1c-hub commented on src/main/java/mate/academy/bookstore/mapper/BookMapper.java
> +import org.mapstruct.Mapper;
Packaging lgtm, dunno what I could change with it

2024-04-23 21:08 UTC, rel1c-hub commented on src/main/java/mate/academy/bookstore/dto/BookDto.java
> +    private String coverImage;
my bad, resolved

2024-04-24 09:01 UTC, karma-o requested changes
left a couple minor comments

2024-04-24 09:01 UTC, karma-o commented on src/main/java/mate/academy/bookstore/model/Book.java
> +@Setter
we should also not forget about equals, hashcode & toString

2024-04-24 09:01 UTC, karma-o commented on src/main/java/mate/academy/bookstore/repository/impl/BookRepositoryImpl.java
> +        }
let's add `Exception` catch block just in case

2024-04-24 09:01 UTC, karma-o commented on src/main/resources/application.properties
> +server.port=8081
any reason to not use the standard one?

2024-04-24 09:01 UTC, karma-o commented on src/main/java/mate/academy/bookstore/serivce/impl/BookServiceImpl.java
> +        return bookMapper.toDto(book);
a small but pretty suggestion 😉 
```suggestion
        return bookRepository.findById(id)
                .map(bookMapper::toDto)
                .orElseThrow(
                    () -> new EntityNotFoundException("Can't find book by id" + id));
```

2024-04-24 11:29 UTC, rel1c-hub commented on src/main/resources/application.properties
> +server.port=8081
I found this solution on the stack; when I start the app on 8080, I always get an error: "port is already in use."

2024-04-25 08:24 UTC, karma-o commented on src/main/resources/application.properties
> +server.port=8081
that means that you already have some Spring boot application running on your PC that is using that port, thus not allowing your to to run it again, you probably have either booted this application as a usual run, and in debug at the same time, or you quit the IDEA without terminating the program, just restart your PC and the problem should be gone, and let's remove this line of code after that

2024-04-25 08:26 UTC, karma-o approved these changes

2024-04-26 13:18 UTC, merged