feat : created initial version of a README
rel1c-hub/book-store pull request #26
Opened 2024-05-29 21:01 UTC by rel1c-hub

2024-05-30 11:09 UTC, yevheniisynytsia requested changes

2024-05-30 11:09 UTC, yevheniisynytsia commented on README.md
> +b# Book Store Project
```suggestion
# Book Store Project
```

2024-05-30 11:09 UTC, yevheniisynytsia commented on README.md
> +    - For admin features, use credentials:
let's say that a client can use either basic auth, or jwt bearer token

2024-05-30 11:09 UTC, yevheniisynytsia commented on README.md
> +
let's add one more thing - for example author model with detailed info or similar

2024-05-30 11:09 UTC, yevheniisynytsia commented on README.md
> +## Possible Improvement
I would also like to see some part about the challenges you've faced and how you overcame those

2024-06-19 08:27 UTC, karma-o requested changes
Looking good but still have to make some fixes

2024-06-19 08:27 UTC, karma-o commented on README.md
> +- 🟥 **DELETE** `/books/{id}`: Delete book.
I do not understand why some requests are red and some are yellow, so please add a legend(explanation) of the color-coding at the top of that topic

2024-06-19 08:27 UTC, karma-o commented on README.md
> +![Database Diagram]
you should push the image to the git as well(some "readme resources" folder in the root of the project) to be able to see it on the GitHub and not only on your local env

2024-06-19 08:27 UTC, karma-o commented on README.md
> +   ```
redundant space and wrong file type
```suggestion
  ```env
  MYSQLDB_USER=root 
  MYSQLDB_ROOT_PASSWORD=root 
  MYSQLDB_DATABASE=test_db 
  MYSQLDB_LOCAL_PORT=3307 
  MYSQLDB_DOCKER_PORT=3306 
  SPRING_LOCAL_PORT=8088 
  SPRING_DOCKER_PORT=8080 
  DEBUG_PORT=5005
  ```
```

2024-06-19 08:27 UTC, karma-o commented on README.md
> +## Possible Improvement
agree, would be nice to have it

2024-07-11 12:15 UTC, merged